import {cp, mkdir, readFile, rm, writeFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import path from 'node:path';
import process from 'node:process';

const projectRoot = process.cwd();
const uuid = 'quota-glance@geequlim';
const compiledRoot = path.join(projectRoot, '.build-js');
const outputRoot = path.join(projectRoot, 'build', uuid);
const schemaSource = path.join(
  projectRoot,
  'schemas',
  'org.gnome.shell.extensions.quota-glance.gschema.xml',
);

await rm(outputRoot, {recursive: true, force: true});
await mkdir(outputRoot, {recursive: true});

await cp(compiledRoot, outputRoot, {recursive: true});
await cp(path.join(projectRoot, 'metadata.json'), path.join(outputRoot, 'metadata.json'));
await cp(path.join(projectRoot, 'stylesheet.css'), path.join(outputRoot, 'stylesheet.css'));
await cp(path.join(projectRoot, 'LICENSE'), path.join(outputRoot, 'LICENSE'));
await cp(path.join(projectRoot, 'icons'), path.join(outputRoot, 'icons'), {
  recursive: true,
});

const schemaOutput = path.join(outputRoot, 'schemas');
await mkdir(schemaOutput, {recursive: true});
await cp(schemaSource, path.join(schemaOutput, path.basename(schemaSource)));

const schemaCompile = spawnSync('glib-compile-schemas', [schemaOutput], {
  encoding: 'utf8',
  stdio: 'pipe',
});
if (schemaCompile.status !== 0) {
  throw new Error(schemaCompile.stderr || 'glib-compile-schemas failed');
}

const metadata = JSON.parse(await readFile(path.join(outputRoot, 'metadata.json'), 'utf8'));
if (metadata.uuid !== uuid) {
  throw new Error(`metadata UUID must be ${uuid}`);
}

await writeFile(
  path.join(outputRoot, '.build-info'),
  'Generated by npm run build. Do not edit this directory directly.\n',
);

console.log(`Built ${path.relative(projectRoot, outputRoot)}`);
